### ISSUE TITLE
JABX error from CLI importer/exporter

### ISSUE THREAD

**Issue by subotaih** [3dcitydb/importer-exporter#107]
Hi,

I'm using CLI to import GML files everyday on a linux server.
However, since few days, scripts are not working anymore, because someone updated the Java version to Java 11. 

Here the error log :
`Erreur : impossible d'initialiser la classe principale org.citydb.ImpExp
Causé par : java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

It's means something like  `Error: Could not initialize main class org.citydb.ImpExp.
Caused by : java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

And and extract of the scripts used to import the gml files : 
`for file in ~/importer-exporter-3.3.1/data/Building/*.gml 
do 
  java -jar ~/importer-exporter-3.3.1/lib/3dcitydb-impexp.jar -shell -config ~/importer-exporter-3.3.1/data/config.xml  $file
done`

From what i've seen, the bug comes from the fact that Java 11 do not supports JABX anymore.

**What i tried to resolve the problem :** 

- Adding `-import --add-modules java.xml.bind` to force him use this module **--- Didn't worked**

- Updating the importer/exporter to 4.2.2    **--- Didn't worked**

- Adding the module dependency to the "build.gradle" of the imp/exp client and rebuild  **---- Didn't worked**

**Comment by clausnagel** [comment]
You're right, Java 11 does not include JAXB anymore. In order to support Java 11 and higher, we have added JAXB as separate library dependency to the Importer/Exporter already in version 4.0. If you install the latest version 4.2.2 and check the `lib` folder, you will find the JAXB libraries in there.

So, updating to version 4.2.2 should solve your problem. I just ran this version on my machine with Java 11 and had no issues. Do you get any error messages when using the 4.2.2 release?

**Comment by subotaih** [comment]
> Do you get any error messages when using the 4.2.2 release?
Yes, i have the same error message, i could not find the `jaxb-api-2.3.1.jar` in the `\impexp-client\build\lib` folder after building from source with gradle.

But after building and using the installer I was able to find the file in `lib`. 

I'd know tomorrow if it worked. I'll keep you informed, thanks !

**Comment by subotaih** [comment]
Problem solved, thanks again !
