### ISSUE TITLE
Disabling spatial and normal indexes

### ISSUE THREAD

**Issue by sschoenhardt** [3dcitydb/importer-exporter#120]
Hello and thank you for visiting my issue.
I am attempting to populate a very large database (essentially the entire US) and after importing the buildings for one city, the GML import times began to take exceptionally long. I then set the preferences to deactivating spatial and normal indexes before import and reactivating them after import as suggested in the documentation, and that seems to have alleviated the issue. However, it seems that as the database gets large and larger, activating the indexes takes considerably more and more time. While the importation process is back to a "normal" speed, the index activation process can take from 10 to 20 minutes. Can someone please first help me understand the consequences of disabling both the spatial and normal indexes before import? And then, is there any potential solution to that I could implement to speed up the importation process?
Thank you for your time!

**Comment by clausnagel** [comment]
Spatial indexes are dynamically updated and rebuilt during an import operation. This is simply an expensive operation (both on PostgreSQL/PostGIS and Oracle) and may slow down the import operation, especially if the `SURFACE_GEOMETRY` table is large like in your case. 

A standard workaround is to drop the spatial indexes before an import because then nothing needs to be dynamically updated, and to recreate the indexes afterwards. Of course, building the indexes from scratch also takes time. So, this workaround makes especially sense for bulk imports, but not for small and frequent imports.

The 3DCityDB per default creates spatial indexes on the columns `geometry` and `solid_geometry` of the table `surface_geometry` and another one on the column `envelope` of the table `cityobject`. Only the latter is required for BBOX queries on the database. Thus, if you never run spatial queries against the `surface_geometry` table, you could permanently drop those two indexes. I guess this should already make a considerable difference. 

Note that even if you manually drop the two indexes, the Importer/Exporter would automatically recreate them if you use the spatial index operations on the `Database` tab or the corresponding import preference settings. To prevent the Importer/Exporter from doing so, all you have to do is to delete the corresponding index object entries from the `index_table` in the `citydb` schema of the 3DCityDB. This table is just a metadata table mainly used by the Importer/Exporter. 

Of course, you could and should also tune your database. For instance, increase the memory settings for `work_mem` and `maintenance_work_mem`.

**Comment by clausnagel** [comment]
Closind due to inactivity. Feel free to re-open if you have further questions.
