### ISSUE TITLE
Error validation GML file using 3DCityDB

### ISSUE THREAD

**Issue by Lam-V-Nguyen** [3dcitydb/importer-exporter#134]
Hi everyone,

I am using FME to export the Sketchup into the CityGML file. I can see buildings on the FZKViewer perfectly (with the ground, wall, and roof surfaces have been separated correctly). I imported this CityGML file into the 3DCityDB and validation progress was fine.
But when I imported it to the database, I got some errors related to XLink reference (as an attachment). I knew that these errors appeared because there were not relevant reference addresses in the CityGML file.
How can I fix this in the FME file?
Thanks in advance.

Best.

![Figure2](https://user-images.githubusercontent.com/53025581/93097515-f9405100-f6a5-11ea-9d13-0454be7739c8.JPG)

**Comment by clausnagel** [comment]
Hi  @Lam-V-Nguyen, the error messages mean that your CityGML file contains references to features and/or geometries but the referenced objects are missing in your file. In CityGML, references are expressed using the `gml:id` of the target object. 

For example, when you want to assign a texture to a polygon, you have to reference the target polygon from the `app:ParameterizedTexture` element via its `gml:id`. If your dataset contains such a reference, but no polygon in your dataset has the referenced `gml:id`, the importer will give you the above "Failed to resolve XLink reference ..." error message. Note that an XML validation will not reveal unresolvable references.

Interestingly, missing references in FME-generated CityGML datasets are also reported in #27. This seems to be an FME issue rather than an importer issue. I instead assume that the importer behaves correctly.

Well, maybe you can just safely ignore these errors? Or fix your FME workspace?

**Comment by MattSmillie** [comment]
This discussion has taken place over here: https://community.safe.com/s/question/0D54Q000086CbyoSAC/ask-for-exporting-citygml-file?t=1600415389056
The issue with what created the problem from FME isn't clear. The data are double sided Textured lod2MultiSurface Buildings. The file also contains unlinked wall, ground and roofsurfaces. Both the buildings and boundedBy surfaces share the same textures. In addition to textures there also look to be some materials defined. 
The question could be posted to Safe software support to find out why there are unreferenced appearances. 
I will close the issue here as the discussion can continue on the FME Community. If an answer it found then I will update the issue.
