### ISSUE TITLE
update splash and partner icon due to new company logo of VCS 

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#140]

**Comment by yaozhihang** [comment]
Done in the PR https://github.com/3dcitydb/importer-exporter/pull/149. Close this issue after merge

**Comment by BWibo** [comment]
Hey, 
the image of the solar potential analysis with trees is not the best quality in the spash window.
I could provide a new one, we have a nice vegetation model from Munich now, this could be an option:

![solar-tum](https://user-images.githubusercontent.com/7643434/101342715-40904500-3883-11eb-80f6-a45d7e6a3040.png)

**Comment by yaozhihang** [comment]
@BWibo thanks for providing the new image. looks very good. @Son-HNguyen would you like to look into this?

**Comment by Son-HNguyen** [comment]
@BWibo @yaozhihang I actually prefer the existing splash, it's not perfect in any way but more balanced in terms of colors. But it could just be my own personal preferences. I'm open if others would like to update the splash.

![splash](https://user-images.githubusercontent.com/5765503/101540466-59424d00-39a0-11eb-8e2a-d17dff042423.png)

**Comment by yaozhihang** [comment]
Yes, the current one looks better in terms of color balance and contrast. :-)

**Comment by Son-HNguyen** [comment]
@clausnagel @yaozhihang Is it just me or does the installer splash look too pixelated in the current branch `export-vis-cli`? Perhaps this is what @BWibo meant that it doesn't have good resolution. I think the splash itself is fine regarding the resolution, but somehow it is shown more pixelated in the installer. Also the texts are too small on my screen (2560x1440).

![image](https://user-images.githubusercontent.com/5765503/101542518-29e10f80-39a3-11eb-8c33-ad82d6407470.png)
![image](https://user-images.githubusercontent.com/5765503/101542807-a116a380-39a3-11eb-8ac1-a2a6ce1d5ca6.png)

**Comment by clausnagel** [comment]
I can confirm the small font size on my resolution (3840 x 2160) as well, which makes the installer hardly readable. But the splash image itself looks fine and is not pixelated an my screen. We use IzPack 4.3.5 for building the installer. It only has few options to influence the UI look&feel. Anything beyond these predefined options would require rebuilding IzPack from source.

**Comment by BWibo** [comment]
Yes, there is nothing wrong with the image in general, but it looked pixelated in the splash screen. Possibly, this is cause by scaling options from Windows i use.

**Comment by clausnagel** [comment]
The pixelation of the image depends on the screen resolution and the screen scale factor. Since the installer only uses default Java methods for loading and displaying images, I am not sure if we can really change this behaviour. I at least hacked the installer to use FlatLaf as default look&feel (1de27c742c6839f935eb66edc14165630f72f425). This way, the font size correctly scales with the screen scale factor. Of course, if you use a large resolution with 100% scaling factor, then your font size will be small.

But coming back to the original discussion: do we all agree that we will use the current splash screen (old image + new VCS logo)? Or will we go with a completey new image? In the latter case, I would prefer to use a new topic for the image instead of solar irradiation.

Well, since the splash screen was always contributed by TUM so far, what do you think @Son-HNguyen, @BWibo, @thomashkolbe?

**Comment by Son-HNguyen** [comment]
@thomashkolbe and I had a small discussion last week and we at TUM agreed to use the current splash screen (with the new VCS logo) as it is right now.

**Comment by BWibo** [comment]
Yes, I would stick to the current one as well as the image quality issue does not have to do with the image itself.
