### ISSUE TITLE
Acess problems with new user. CityGML Export

### ISSUE THREAD

**Issue by Flodkvist** [3dcitydb/importer-exporter#167]
New users cant make CityGML exports.

I´ve set up a new database user. Granting RO access using GRANT_ACCESS.bat
In my atempts, the new users can sucessfully use "KML/COLLADA/glTF Export".
But when exporting to CityGML I get an error.

> [13:16:04 ERROR] Failed to query the database.
> [13:16:04 ERROR] org.postgresql.util.PSQLException: FEL: rättighet saknas för schema citydb
>   Position: 23

( translation: ERROR: rights missing for schema citydb )

Using Postgres v.12
importer-exporter v.4.2.3
3dCityDB v.4.0.3
Windows 10 / Windows Server 2019

The new Postgres user:
```
CREATE ROLE iread WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  REPLICATION
```

Checking the schema citydb
`GRANT USAGE ON SCHEMA citydb TO iread;`

**Comment by clausnagel** [comment]
Thanks for reporting, @Flodkvist. The export process uses a cache to be able to resolve geometry and feature XLinks as well as global appearances. This cache is held in main memory and, by default, is drained to the database if cache limits are reached. For this purpose, temporary tables are created in the `citydb` schema for storing the cache information and dropped after export has finished.

A RO user is, however, not allowed to create these cache tables. That's why the export fails with error messages. This is a bug and needs to be fixed but it will take us some time because the caching mechanism is a core functionality.

Here are two workarounds for the meantime:

1. You can choose to drain the cache to the local file system instead of the database. Please use the `"Global > Cache"` settings on the `Preferences` tab for this purpose. This will already solve the issue in most cases. However, if your 3DCityDB contains global appearances, then some temporary information must go into the database because we use SQL joins to resolve global appearances. So in this special case, you will still run into errors because some temporary tables need to created in the database.

2. You can grant usage and create privileges on the `citydb` schema:
    ```
    GRANT USAGE, CREATE ON SCHEMA citydb TO iread;
    ```
    This will enable the `iread` user to create temporary tables. And since the user has still only `SELECT` privileges on the 3DCityDB tables, there is no way that the user can perfom `INSERT`, `DELETE`, `TRUNCATE`, or `DROP` operations on these tables.

You can even combine both workarounds.

We will check the best way how to solve this issue for a future version. For example, we could add another `citydb_tmp` schema that is just used for temporary information.

Hope this helps.

**Comment by Flodkvist** [comment]
Thank you so much for the detailed and well formulated response @clausnagel 

I will try theese workarounds.

The user is also intended to be used for access from visualization service (Bentleys Open Cities Planner). I hope theese workarounds solves that too.

I will report how things go, if for nothing else, future reference to other users searching for answers.

**Comment by clausnagel** [comment]
Ah, interesting use case to directly connect to Bentley software. I am not sure how the Open Cities Planner queries and retrieves data from the 3DCityDB. Depending on how it is implemented, it might not even need to create temporary tables, and you might not run into issues.

Yes, I would be happy if you report back your experiences.

Cheers.

**Comment by clausnagel** [comment]
Thanks for your feedback. Yes, the new release now implements solution 2.

Closing this issue now. If there is more we can do to help you connect Bentley OCP with 3DCityDB, let us know.
