### ISSUE TITLE
Possible bug in (textured) relief feature export?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#18]
Hi,

I guess there is a little bug in the export function of the importer/exporter when it comes to exporting a triangulated relief feature with textures.

The issue seems to be that during export the gmlid of the triangles (linestrings) are added a "_0_", but this is not consistently done in the appearance.
Hence, when importing a dataset previously exported, you get an error message due due unresolved XLinks.

I have prepared a little example. In the zipped file (see later) you find the original input gml (tin_example.gml) and the corresponsing export (tin_example_export.gml).
You can import the first one, export it, but you cannot reimport the second one.

Is this a bug or am I  doing something wrong?

Greetings,

GA

[tin_in_out_example.zip](https://github.com/3dcitydb/importer-exporter/files/505905/tin_in_out_example.zip)

**Comment by clausnagel** [comment]
This is a known limitation of the CityGML exporter. I think it is mentioned somewhere in the documentation (at least it should be mentioned). Resolving this limitation requires changes to the export of XLink references. Let's see whether we can change this with the next version.

For the time being, the recommended work-around is to use `GeoreferencedTexture` for the terrain rather than a `ParameterizedTexture` element for every triangle. This would also dramatically reduce the file size of your CityGML document.

**Comment by clausnagel** [comment]
Postponed to the next major version 6.0 of the Importer/Exporter.
