### ISSUE TITLE
Error: Ring contains less than 4 coordinates and will not be imported.

### ISSUE THREAD

**Issue by ozaapt** [3dcitydb/importer-exporter#204]
Hello,
when i try import my gml file, i get this error
![image](https://user-images.githubusercontent.com/87305472/125891924-fcf9e85d-e987-42bb-80b6-45f662e2ab30.png)

but when i upload my file cesium https://cesium.com/ion , it work properly
![image](https://user-images.githubusercontent.com/87305472/125892090-56f5b398-11b8-40fa-9be1-f394b74f282f.png)

**Comment by clausnagel** [comment]
This is not a 3DCityDB issue, but a data issue. Check the definition of `LinearRing` from GML:

> A LinearRing is defined by four or more coordinate tuples, with linear interpolation between them; the first and last coordinates shall be coincident. The number of direct positions in the list shall be at least four.

To define a surface, you need at least three coordinate tuples (triangle). Since the first and last coordinates must be coincident for a `LinearRing`, you need at at least four. At least some `LinearRing` elements in your data violate this rule. The Importer/Exporter automatically tries and fixes `LinearRing` elements for which the first and last coordinates are not coincident. But even that does not help in your dataset. So, please fix you `LinearRing` elements.

Since those elements are not valid surfaces, you do not see them in Cesium Ion. You only see the valid surfaces.

**Comment by ozaapt** [comment]
i try this file
[FZK-Haus-LoD3-KIT-IAI-KHH-B36-V1.zip](https://github.com/3dcitydb/importer-exporter/files/6828760/FZK-Haus-LoD3-KIT-IAI-KHH-B36-V1.zip)

but i get this result
![image](https://user-images.githubusercontent.com/87305472/125910942-a7173ca5-3c1d-4e73-a82b-cf1be9056802.png)

i try in cesium, this is the result
![image](https://user-images.githubusercontent.com/87305472/125911056-da2a3f0c-e0e2-4173-b971-a51981919958.png)

is my import/export setting wrong?

**Comment by clausnagel** [comment]
Yes, the file works fine for me:

![image](https://user-images.githubusercontent.com/5517439/126005545-767edb88-0f2d-40fb-bd23-a630a9b46b5a.png)

Note that the building has height values, and these height values are written to the visualization model by default. Thus, if you  do not use a matching terrain in the viewer, the builing might fly over or lie below the earth surface. You can use the "VIS Export - Elevation" preferences on the "Preferences" tab to influence the exported height values. In my above screenshot, I did not load a terrain, so I checked the option "Move every object on the globe (zero elevation)". With this option, the building is nicely located on the flat globe.

More information can be found in the user manual: https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/export-vis.html
