### ISSUE TITLE
Generic attributes of type measure unsopported in kml balloons?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#210]
Hi,

It seems to me that generic attributes stored in the 3DCityDB as type measure (i.e. with an additional unit of measure) are not exported into GoogleEarth balloons. I suspect this type was added with CityGML 2.0 and it was not added to the exporter - just my educated guess :-)

All the best,

GA

**Comment by thomashkolbe** [comment]
Hi Giorgio, that is a good educated guess. We will have a look at this.

**Comment by clausnagel** [comment]
@thomashkolbe, @Son-HNguyen, have you been looking into this?

**Comment by clausnagel** [comment]
I fixed two of the balloon templates that are shipped as examples with the Importer/Exporter (see [here](https://github.com/3dcitydb/importer-exporter/commit/83eb3d0d60e90260935b6c6831e1a61f29aae949)). Not sure whether this was the original intention of this issue? Because the balloon query language generally supports retrieving generic measure attributes.
