### ISSUE TITLE
delete the city objects

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/importer-exporter#259]
Hi,

I have imported a wrong city object into the DB, can I delete it in the importer/exporter?

Thank you!

**Comment by clausnagel** [comment]
Well, yes and no :-)

No, because the grahpical user interface of the Importer/Exporter has no user dialog for deleting objects.

Yes, because the command-line interface of the Importer/Exporter has full support for deleting objects. Read more in our [online documentation](https://3dcitydb-docs.readthedocs.io/en/version-2022.0/impexp/cli/delete.html)

There are also powerful database-side delete scripts that you can use. You can find them in the `citydb` schema (PostgreSQL) and they are named `del_*`. Read more in our [online documentation](https://3dcitydb-docs.readthedocs.io/en/version-2022.0/3dcitydb/sproc/citydb-delete.html). The CLI of the Importer/Exporter also uses these scripts in the background.
