### ISSUE TITLE
URL and cityobjectsJsonUrl for the JSON files 

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/importer-exporter#270]
Hello,

for the 3D Web Map Client, the URL and cityobjectsJsonUrl, are they always:

http://localhost:8000/3dwebclient/Samples.json
and 
http://localhost:8000/3dwebclient/Samples_extruded_MasterJSON.json?

The tutorial says: The URL of the JSON file which can be generated automatically by using the
KML/COLLADA/glTF Exporter

But I cannot find where.

Thank you

**Comment by BWibo** [comment]
The URLs for the layers depend on where you host the data.
If your webserver is at a different domain or your data in a different subfolder on the server, the URL will be different accordingly. Checkout a basic webserver tutorial if you don't have any experience with webservers.

> The tutorial says: The URL of the JSON file which can be generated automatically by using the
> KML/COLLADA/glTF Exporter

Can you point me to that statement in the docs? That is - as far as I know - not correct.
The URLs are not automatically generated, but the export data is.

**Comment by Ferkelcode** [comment]
Thank you very much for the answer.

The statement is from https://3dcitydb-docs.readthedocs.io/en/version-2021.1/webmap/online-spreadsheet.html section 6.4.4
![image](https://user-images.githubusercontent.com/77849645/188283214-2c89f3db-0623-4494-9154-81a09cbe75a5.png)

**Comment by Ferkelcode** [comment]
If in the VIS Export, I export the 3 files ( kml01_extruded_MasterJSON.json, kml01.kml, kml01.json) the the folder  Desktop\3DCityDB5.2.0\3d-web-map-client\3dwebclient, the URL should be:
http://localhost:8000/3dwebclient/kml01_extruded_MasterJSON.json 

Is this not correct?

I remember I have read this in the tutorial, but I cannot find it anymore.

I have exported the spreadsheet, and got the address for thematicDataUrl. And exported the kml files. I put 
http://localhost:8000/3dwebclient/kml01_extruded_MasterJSON.json  to 'URL'
and 
the google sheet links to 'thematicDataUrl'

Then the 3dwebclient didn't show anything.
Do you know what is the problem?

**Comment by BWibo** [comment]
Thx, the statement in the docs is a bit missleading and should be change (@Son-HNguyen ). 
The `cityobjectsJson` file can be automatically generated, but the URL to that file depends on where you host it using a webserver.

The URLs you posted are not sufficient to resolve this.
As I mentioned before, you will need some basic understanding of webservers to resolve this.

You need to know:
  1. What is the root folder of your webserver?
  2. What domain/ip address and port is your server listening at?
  
Then you can build the correct URLs by combining the information from 1 and 2 and the path of your files relative to the server root folder. For instance, your server is listening at `http://localhost:80` and your server root is `/c/folder` and your file is in `/c/folder/subfolder/myfile.json`, then the URL to the file would be: `Http://localhost:80/subfolder/myfile.json`.

Closing, as this issue is not a Webclient problem.

**Comment by Ferkelcode** [comment]
Thank you, I have checked as you told me. Then with the generated url, I can get the following information:

> {
> 	"version": "1.0.0",
> 	"layername": "kml01",
> 	"fileextension": ".kmz",
> 	"displayform": "extruded",
> 	"minLodPixels": 120,
> 	"maxLodPixels": -1,
> 	"colnum": 1,
> 	"rownum": 1,
> 	"bbox":{ 
> 		"xmin": 5.937952819198381,
> 		"xmax": 46.62039596564427,
> 		"ymin": 42.933776289335235,
> 		"ymax": 51.45619575225303
> 	}
> }


Is this too empty?
As my .xlsx file contains a lot message, but my visulization always shows only a rectangular. 
![image](https://user-images.githubusercontent.com/77849645/190848877-a83dd13c-3044-4105-9487-371d76c7a9c5.png)

Do you know what could be the problem?
