### ISSUE TITLE
Importer/Exporter 5.4.2: ADE manager tab gone?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#300]
Hi guys!

In Ubuntu Linux 22.04, it seems that the ADE manager tab is gone. Abducted from the UFOs? 😀
Still, the ADE is detected and seems to be supported correctly. See screenshot.
Am I missing something?

(I installed the energy ADE with a previous version of the Importer/Exporter)

![image](https://github.com/3dcitydb/importer-exporter/assets/15018017/c40a284e-c6a5-4d4f-8842-b55fe7cec120)

**Comment by clausnagel** [comment]
Your 3DCityDB instance obvioulsy supports the ADE, since - as your write - you have already installed the ADE-specific tables. And the Importer/Exporter doesn't need the ADEManager plugin to support a specific ADE. All you need is an ADE extension in the `ade-extension` folder to get a green check.

So, all good, you can go on without the ADEManager plugin.

**Comment by gioagu** [comment]
Sorry, yes!
Just found out but you were faster!
All fine, sorry. I forgot to add the plugins in the plugin directory

Indeed no UFOs!! :-)

**Comment by yaozhihang** [comment]
Hm, the tab of spreadsheet generator plugin is also missing in your screenshot. Please check the preference settings, whether the plugins are activated. see the following screenshot:
 
![image](https://github.com/3dcitydb/importer-exporter/assets/5942971/98c8d061-9386-4b40-a942-7a9bec39d241)
