### ISSUE TITLE
Citygml export. Land_use cityobject does not have geometries in exported citygml file. Geometry is in 3dcitydb table.

### ISSUE THREAD

**Issue by jsvaataja** [3dcitydb/importer-exporter#309]
Hi !

I have a problem when exporingt the citymodel and I'd like to have land_use cityobject with geometries included. I get following
 <cityObjectMember>
    <luse:LandUse gml:id="LUSE_2334253">
      <gml:name>ShireHill</gml:name>
      <luse:lod1MultiSurface/>
    </luse:LandUse>
  </cityObjectMember>

No geometries included in citygml-file 

surrface_geometry table:
Geometry is polygon Z and it is defined in surface_geometry table.  I have checked the geometry with

select ST_IsValid(geometry),ST_IsClosed(geometry), ST_GeometryType(geometry),ST_IsValidDetail(geometry) from surface_geometry where id = 248223; 

Result:
true	true	"ST_Polygon"	"(t,,)" 

id = 248223
parent_id = null
root_id = 248223
is_solid = 0
is_composite = 0
is_triangulated = 0
is_xlink =0
geometry = the geometry mentioned above
is_reversed = 0
parent = null
cityobject_id = 31067 same as the land_use row_id ( and same as the cityobject_id)

3dcitydb-importer-exported version is 5.4.3. The question is: What I'm doing wrong ?  It's quite possible that my approach is not valid and I'd appreciate very much if someone could give me the guidelines how to overcome this problem.   

Regards, Janne

**Comment by clausnagel** [comment]
Maybe you have found a bug. To understand what is going on and how to possibly fix it, we would need a test dataset to reproduce the behaviour. Can you share a sample dataset? It's sufficient if it just contains one LandUse that causes problems.

**Comment by jsvaataja** [comment]
[land_use.csv](https://github.com/user-attachments/files/16819226/land_use.csv)
[cityobject.csv](https://github.com/user-attachments/files/16819229/cityobject.csv)
[surfacegeometry.csv](https://github.com/user-attachments/files/16819231/surfacegeometry.csv)

Here are the rows in cityobject,land_use and surface_geometry tables. It is quite possible that I have understood wrong how the land_use geometries should be inserted in 3dcitydb. When I inserted the root_id as parent_id it caused export to fail.

**Comment by jsvaataja** [comment]
I removed the parent_id and then impexp exports the land_use like I described in starting comment.

**Comment by clausnagel** [comment]
Gotcha. You don't import a CityGML file but create the LandUse directly in the database.

The issue is that a LandUse object expects a `MultiSurface` geometry but you have only inserted a simple `Polygon` into the "surface_geometry" table. Storing a multi-surface requires one root row for the `MultiSurface` geometry plus one or more child rows for each `Polygon` contained in the multi-surface. So, for your example, two rows must be inserted into "surface_geometry".

How to store and represent the different geometry types is explained in the [3DCityDB online documentation](https://3dcitydb-docs.readthedocs.io/en/latest/3dcitydb/schema/geometry.html). I typically recommend creating a simple CityGML dataset and importing it into the 3DCityDB using the Importer/Exporter. Afterwards, you can check how the import tool populated the different tables. I have created such a CityGML file for your use case: [landuse.zip](https://github.com/user-attachments/files/16823993/landuse.zip)

I have also exported the tables to CSV:
[cityobject.csv](https://github.com/user-attachments/files/16824012/cityobject.csv)
[surface_geometry.csv](https://github.com/user-attachments/files/16824013/surface_geometry.csv)
[land_use.csv](https://github.com/user-attachments/files/16824014/land_use.csv)

Hope this helps.

**Comment by jsvaataja** [comment]
Problem solved, thanks !! In a matter fact I tried same solution (what You described) but it didn't work out, for the reason an other. Now impexp reads the geometries into citygml-file.
