### ISSUE TITLE
CityGml import, invalid content error

### ISSUE THREAD

**Issue by draugnim** [3dcitydb/importer-exporter#32]
Hi,
I'm having trouble importing mu CityGML model with the importer/exporter tool. Here is the link for the .gml file and the error log I get. 

Appreciate any help.

https://drive.google.com/open?id=16E2sjpFDtC1dLWdt7XCtwA0JCkMuT7yl

**Comment by yaozhihang** [comment]
This error is caused by the invalid <imageUri> element values contained in your GML file. A URI shall, at best, not contain the characters like square bracket and space. Also you shall use normal slashes ("/") instead of backslashes ("\\"). For more info please check the websites below:
http://www.datypic.com/sc/xsd/t-xsd_anyURI.html
https://stackoverflow.com/questions/41893073/can-xsanyuri-contain-square-brackets-in-xsd

**Comment by draugnim** [comment]
Thanks @yaozhihang ! That helped.
