### ISSUE TITLE
How to import/export citygml ADE data?

### ISSUE THREAD

**Issue by YinChaoOnline** [3dcitydb/importer-exporter#44]
Hi? I have developed a CityGML ADE for Cadastre(UML and XSD). I am look for help to figure out the roadmap for importing and exporting the Cadastre-ADE examples data into 3d city db.

I have searched the web, but seemly there is no evident infomation about integrating CityGML ADEs into 3d city db?

My superficial roadmap is:
- ADE(XSD, UML, some examples data)
- develop cadastre-ade module for citygml4j just like noise-ade
- let importer-exporter based on the newly devleoped citygml4j
- ？develop postgresql db schemas?( I am not sure for this step)

Can someone point out a reasonable way to accomplish my goal storing/exporting the ade data in postgresql?

**Comment by FxKu** [comment]
Hi YinChao,

We are currently working on bringing ADE support to the 3DCityDB. It will be part of the next major release that we have planned for (early) summer. It will allow you to map your UML schema to database tables (no need to develop a Postgres schema). But, you would still need to implement the Java classes in the Importer/Exporter that fill your schema, but we'll provide an walkthrough example, so that this step should be easy to complete. I'm not so sure about the citygml4j part. Maybe the others can add some infos here.

If you check out the newest version of the Importer/Exporter and the ADE Manager Plugin, you can get an idea, how the support will look like. But as said, it's still under development and some things will probably change until the release. You better wait until then before implementing support for your ADE.

Regards, Felix

**Comment by FxKu** [comment]
The release is out. You can try to map a given ADE into database tables with the new [ADE Manager Plugin](https://github.com/3dcitydb/plugin-ade-manager). To use the the Importer/Exporter or WFS, you have to implement the ADE API in Java. We provide a [generic test example](https://github.com/3dcitydb/extension-test-ade) so that you can understand easily, what has to be done. Please, reach out if some things remain unclean from the docs or code.

**Comment by FxKu** [comment]
Closing this issue now. For new questions regarding the ADE mapping, please open a new request with specific questions on the available tools.
