### ISSUE TITLE
Export a group of CityGML features using a Bounding Box (question)

### ISSUE THREAD

**Issue by jukos** [3dcitydb/importer-exporter#54]
Hello,
I used the Tutorial „3DCityDB_V3.3_Hands-On_Tutorial“.
Exercise 4.1 export of one or several buildings are no problem.
I open the results within the software FZKviewer. All OK.
But.....
if I want to use the bounding box, I get errors:
After click on „apply“ (übernehmen):
_[18:16:47 ERROR] Failed to transform bounding box to WGS 84: FEHLER: Input geometry has unknown (0) SRID
[18:17:03 ERROR] Failed to transform bounding box to WGS 84: FEHLER: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert_

Another try I got the message 
_[16:56:05 INFO] Database export successfully finished._
but the gml file is only 3kb without buildings. FZKViewer have only 0 values for model boundingbox (SRS Dialog).

What should I change to get any result? Any ideas?

Thank you and greetings,
Jürgen

I use:
Windows 10, PostgreSQL, local system

**Comment by FxKu** [comment]
Hi,
what Bounding Box did you use? Did you copied the values of the tutorial into the text field or did you created your own box? Internally, the error message happens when executing the following statement:

```sql
SELECT ST_Transform(ST_GeomFromEWKT('SRID=<source_srid>;POLYGON((<your_coordinates>))'), 4326)
```

If the source SRID is 0, you get this error. Now, I wonder why it is 0? I might be that you did not enter a valid SRID when setting up the database. Simply check the `geometry_columns` view of PostGIS. If the SRID id 0 this would also explain, why no building are exported when using the bounding box filter with values of WGS84.

Cheers.

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open if the problem still exists.
