### ISSUE TITLE
Display semantic information without using Google Fusion Table

### ISSUE THREAD

**Issue by fthill61** [3dcitydb/importer-exporter#83]
Hello, 
I would like to know if it is possible to display data with thematic informations (attributes etc.) without using a cloud solution like Google Fusion Table ? Is there any way to store the spreadsheet file (created with SPSHG) locally and call it with the "localhost/8000/..." adress ? 

Thank you, 

Florian

**Comment by Son-HNguyen** [comment]
Hi Florian,

Google Fusion Tables were used as a means for users to share thematic information of their city models with other users online without having to host the data themselves. 

It is currently not possible to store a table locally and load it in the web client as if it were hosted by Google Fusion Tables. Please note that even it were possible, the table wouldn't be accessible for other users (in case you want to share your project), unless you host your table in some public server, which will then probably cause the CORS problems.

Nevertheless, since Google Fusion Tables is shutting down at the end of 2019 anyway, all alternatives (including your suggestion) are being considered. So stay tuned. :)

Son

**Comment by yaozhihang** [comment]
solved in the 3dcitydb-web-map v1.8.1 by adding the support of PostgREST service. More details here (https://github.com/3dcitydb/3dcitydb-web-map/blob/master/CHANGES.md)
